package TiendaBarrioAppMven.infrastructure.lasting;

public enum ELabel {
    AMBIENTADORES("Ambientadores"),
    BLANQUEADORES("Blanqueadores"),
    CERA("CERA"),
    DESINFECTANTES("desinfectantes"),
    INSECTICIDAS("Insecticidas"),
    LIMPIEZA("Limpieza de Superficies"),
    AGUA("AGUA"),
    ENERGIZANTES("Energizantes"),
    GASEOSAS("Gaseosas"),
    HIDRATANTES("Hidratantes"),
    JUGOS_MALTAS("Jugos, Refrescos y Maltas"),
    TE_LIQUIDO("Te Liquido"),
    CONGELADOS("Congelados"),
    EMPANADAS("Empanadas"),
    PAPAS_YUCAS_Y_PAQUETES("Papas, yucas y Paquetes"),
    CIGARRILLOS("Cigarrillos"),
    ALIMENTACION("Alimentacion"),
    PANALES("Pañales"),
    PANITOS("Pañitos"),
    AFEITADO("Afeitado"),
    CREMAS_CORPORALES("Cremas Corporales"),
    CUIDADO_ORAL("Cuidado Oral"),
    DESODORANTES("Desodorantes"),
    GEL("Gel"),
    JABONES_DE_TOCADOR("Jabones de Tocador"),
    PAPEL_HIGIENICO("Papel Higienico"),
    PROTECCION_FEMENINA("Proteccion Femenina"),
    SHAMPOO("Shampoo"),
    DETERGENTES("Detergentes"),
    JABONES_EN_BARRA("Jabones en Barra"),
    ACEITES("Aceites"),
    ARROZ_Y_GRANOS("Arroz y Granos"),
    AVENA_HOJUELA("Avena en Hojuelas"),
    AZUCAR_Y_PANELAS("Azucar y Panelas"),
    BASES_CREMAS_Y_SOPAS("Bases, Cremas y Sopas"),
    BASES_ACHOCOLATADAS("Bebidas Achocolatadas en Polvo"),
    CAFE("Cafe"),
    CEREALES("Cereales"),
    CHOCOLATES_DE_MESA("Chocolates de Mesa"),
    CONDIMENTOS_CALDOS_Y_SAL("Condimentos,caldos y sal"),
    ENLATADOS_CONSERVAS("Enlatados y Conservas"),
    HARINAS_Y_MEZCLAS("Harinas y Mezclas"),
    PASTAS("Pastas"),
    SALSAS_VINAGRES("SALSAS_Y_VINAGRES"),
    TE_INFUSIONES_E_INSTANTANEOS("Te, infusiones e instantaneos"),
    SALUD_BIENESTAR("Salud  y Bienestar"),
    AREQUIPE("Arequipe"),
    CHOCOLATERIA("Chocolateria"),
    CONFITES_DULCES("Confites y dulces"),
    CREMA_DE_LECHE_Y_CONDENSADA("Crema de Leche y Leche Condensada"),
    DULCES_TIPICOS("Dulces Tipicos"),
    GELATINAS_FLANES_PUDINES("Gelatinas, flanes y pudines"),
    REPOSTERIA("Reposteria"),
    ELECTRODOMESTICOS("Electrodomesticos"),
    HELADOS("Helados"),
    DESECHABLES("Desechables"),
    BOMBILLOS("Bombillos"),
    PILAS("Pilas"),
    ALPINETTE("Alpinette"),
    ALPINITO("Alpinito"),
    AREPAS("Arepas"),
    AVENA("Avena"),
    CARNES_FRIAS_Y_EMBUTIDOS("Carnes frias y Embutidos"),
    GELATINAS_FLANES_Y_PUDINES("Gelatinas, flanes y pudines"),
    HUEVOS("Huevos"),
    KUMIS("Kumis"),
    LECHE("Leche"),
    LECHES_EN_POLVO("Leches en Polvo"),
    MANTEQUILLA("Mantequilla"),
    MARGARINAS("Margarinas"),
    QUESOS("Quesos"),
    YOGURT("Yogurt"),
    BOLSAS_DE_BASURA("Bolsas de Basura"),
    ESPONJAS_Y_FIBRAS("Esponjas y Fibras"),
    LAVALOZA("Lavaloza"),
    SERVILLETAS("Servilletas"),
    TRAPEROS_ESCOBAS("Traperos o Escobas"),
    AVES("Aves"),
    GATOS("Gatos"),
    HAMSTERS("Hamsters"),
    PERRO("Perro"),
    PEZ("Pez"),
    PANADERIA_EMPACADA("Panaderia Empacada"),
    GALLETAS_DULCES("Galletas Dulces"),
    GALLETAS_SALADAS("Galletas Saladas"),
    GALLETAS_SALUDABLES("Galletas Saludables"),
    PAPAS_FRITAS_Y_PAQUETES("Papas Fritas y Paquetes"),
    AGUARDIENTE("Aguardiente"),
    BRANDY("Brandy"),
    CERVEZA("Cerveza"),
    GINEBRA("Ginebra"),
    LICOR("Licor"),
    RON("Ron"),
    VINOS("Vinos"),
    VODKA("Vodka"),
    WHISKY("Whisky");


    private final String valueLabel;

    ELabel(String valueLabel) {
        this.valueLabel = valueLabel;
    }


    public String getValueLabel() {
        return valueLabel;
    }


}


